### ISSUE TITLE
Look in multiple locations for .db files, prompt if not found

### ISSUE THREAD

**Issue by christopher-dG** [christopher-dG/unnoticed#1]
Windows:
* [x] C:\Users\Username\AppData\Local\osu!

Or better yet, just make it interactive if it's not found in a default location.

**Comment by AdrienBoitelle** [comment]
A lot of people might have it on their C drive root like me : C:\osu!
Maybe also on D or any second drive as it's the HDD most of the time and osu! can grow quite high (my main computer has a 200GB installation of osu, so it's on D:\osu!)
