### ISSUE TITLE
Get newly generated replays from Data/r

### ISSUE THREAD

**Issue by flesnuk** [christopher-dG/unnoticed#17]
I see that you are extracting the replays from replays.db but osu! also stores .osr files in the Data/r folder (it creates a new osr when the user exits from the result screen). I used it for detecting new replays in [biku](https://github.com/flesnuk/biku) which can be useful to you aswell ( [here](https://github.com/flesnuk/biku/blob/master/osuhm/replaynotifier.go) is the file where I do it )

**Comment by christopher-dG** [comment]
Oh nice, I didn't know that. Should be really useful, thanks! Also, very cool work on biku. 👍
